### ISSUE TITLE
Are we using CDN correctly

### ISSUE THREAD

**Issue by neerajdotname** [bigbinary/neeto-compliance#119]
https://www.loom.com/share/02a74deb9bb34b33a20cb9dd21e5737a

**Comment by unnitallman** [comment]
@neerajdotname We are using it correctly. Wappalizer is not showing it because we have multiple CDN's on our pages now. `jsdliver` is another CDN being used for  Remixicons. This will be removed soon, we are working on it already since we have our own neeto icon set now. Once this is removed, I believe Wappalyzer will start showing Cloudfront as CDN.
